name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
    collapse-after: 3
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'maintenance'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'documentation'
      - 'maintenance'
  default: patch

autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?:/i'
  - label: 'bug'
    title:
      - '/^fix(\(.+\))?:/i'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?:/i'
  - label: 'maintenance'
    title:
      - '/^chore(\(.+\))?:/i'
      - '/^refactor(\(.+\))?:/i'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
