name: Feature Request
description: Suggest a new feature for Herald
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this feature solve? What's your use case?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Is this specific to a platform?
      options:
        - All platforms
        - macOS
        - Windows
        - Linux
    validations:
      required: true
